[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
anchor_vault = "6zXc91w7VDjoZ8Dh6i3Tmrt95hsPGj8FjrBJuZDbnLXP"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/theoroque/.config/solana/cli/key.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
