[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
anchor_escrow = "Aqz3Njf8qMpEx5KTU6y1bSogmRLtq5M8HhDJ4KpgNJDu"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/cli/key.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
