[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
capstone_daocre8 = "AwjhMae1WRzopt1CvbCxnHbwys11yqdFTiJtNgTRgzJR"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/theointech/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
